sudo: required

services:
  - docker

language: go

go:
  - 1.13.7

cache:
  directories:
    - .cache
    - $HOME/.build
    # cache the Go module cache
    - $HOME/go/pkg/mod
    # cache `go install`-ed binaries across stages. build.sh unsets GOPATH
    # so this is hitting the default go env of $HOME/go
    - $HOME/go/bin

# Only build for master and branches that look like versions. This also covers
# tags, which keeps us from building (and deploying) from the extra tags we set
# during a release for go multi-module repo support (i.e. proto/spire/v1.2.3).
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?$/

stages:
  - blah

jobs:
  include:
    - stage: blah
      os: linux
      dist: xenial
      script:
        - test/integration/test-one.sh test/integration/suites/datastore-mysql
